//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestService.CalculatorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculatorService.ICalculator")]
    public interface ICalculator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/DoWork", ReplyAction="http://tempuri.org/ICalculator/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/DoWork", ReplyAction="http://tempuri.org/ICalculator/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/add", ReplyAction="http://tempuri.org/ICalculator/addResponse")]
        int add(int n1, int n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/add", ReplyAction="http://tempuri.org/ICalculator/addResponse")]
        System.Threading.Tasks.Task<int> addAsync(int n1, int n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/sub", ReplyAction="http://tempuri.org/ICalculator/subResponse")]
        int sub(int n1, int n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/sub", ReplyAction="http://tempuri.org/ICalculator/subResponse")]
        System.Threading.Tasks.Task<int> subAsync(int n1, int n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/div", ReplyAction="http://tempuri.org/ICalculator/divResponse")]
        int div(int n1, int n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/div", ReplyAction="http://tempuri.org/ICalculator/divResponse")]
        System.Threading.Tasks.Task<int> divAsync(int n1, int n2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculatorChannel : TestService.CalculatorService.ICalculator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorClient : System.ServiceModel.ClientBase<TestService.CalculatorService.ICalculator>, TestService.CalculatorService.ICalculator {
        
        public CalculatorClient() {
        }
        
        public CalculatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public int add(int n1, int n2) {
            return base.Channel.add(n1, n2);
        }
        
        public System.Threading.Tasks.Task<int> addAsync(int n1, int n2) {
            return base.Channel.addAsync(n1, n2);
        }
        
        public int sub(int n1, int n2) {
            return base.Channel.sub(n1, n2);
        }
        
        public System.Threading.Tasks.Task<int> subAsync(int n1, int n2) {
            return base.Channel.subAsync(n1, n2);
        }
        
        public int div(int n1, int n2) {
            return base.Channel.div(n1, n2);
        }
        
        public System.Threading.Tasks.Task<int> divAsync(int n1, int n2) {
            return base.Channel.divAsync(n1, n2);
        }
    }
}
